{{- if .Values.secrets }}
{{- $hasDirectValues := false }}
{{- range .Values.secrets }}
{{- if .value }}
{{- $hasDirectValues = true }}
{{- end }}
{{- end }}
{{- if $hasDirectValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockchain-exporter.fullname" . }}-secrets
  labels:
    {{- include "blockchain-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{- if .value }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}

